UV ?= uv
UV_RUN ?= $(UV) run
APP ?= app.main:app
HOST ?= 0.0.0.0
PORT ?= 8020
MSG ?= new_migration

.DEFAULT_GOAL := help

.PHONY: help install env db-up db-down db-logs migrate migrate-create migrate-downgrade \
	run run-prod lint format format-check typecheck test check pre-commit secrets \
	docker-up docker-migrate docker-down clean

help: ## Show available commands
	@awk 'BEGIN {FS = ":.*##"; print "Available targets:"} /^[a-zA-Z0-9_.-]+:.*##/ {printf "  %-18s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install: ## Install dependencies
	$(UV) sync

env: ## Create .env from .env.example if missing
	@test -f .env || cp .env.example .env

db-up: ## Start PostgreSQL only
	docker compose up -d db

db-down: ## Stop PostgreSQL container
	docker compose stop db

db-logs: ## Tail PostgreSQL logs
	docker compose logs -f db

migrate: ## Apply database migrations
	$(UV_RUN) alembic upgrade head

migrate-create: ## Create a new autogenerated migration (use MSG="...")
	$(UV_RUN) alembic revision --autogenerate -m "$(MSG)"

migrate-downgrade: ## Roll back one migration
	$(UV_RUN) alembic downgrade -1

run: ## Run API with hot reload
	$(UV_RUN) uvicorn $(APP) --reload --host $(HOST) --port $(PORT)

run-prod: ## Run API without reload
	$(UV_RUN) uvicorn $(APP) --host $(HOST) --port $(PORT)

lint: ## Run Ruff checks
	$(UV_RUN) ruff check .

format: ## Auto-format code with Ruff
	$(UV_RUN) ruff format .

format-check: ## Check code formatting
	$(UV_RUN) ruff format --check .

typecheck: ## Run MyPy
	$(UV_RUN) mypy app

test: ## Run tests
	$(UV_RUN) pytest

check: lint typecheck test ## Run lint + type-check + tests

pre-commit: ## Run pre-commit hooks on all files
	$(UV_RUN) pre-commit run --all-files

secrets: ## Run detect-secrets hook manually
	$(UV_RUN) pre-commit run detect-secrets --hook-stage manual --all-files

docker-up: ## Start full stack (db → migrate → api). Ports: API_PUBLISH_PORT / POSTGRES_PUBLISH_PORT
	docker compose up --build

docker-migrate: ## Run alembic upgrade head inside Compose (against the db service)
	docker compose run --rm migrate

docker-down: ## Stop and remove Docker stack
	docker compose down

clean: ## Remove Python cache artifacts
	find . -type d -name "__pycache__" -prune -exec rm -rf {} +
	find . -type f -name "*.pyc" -delete
