"""fix_transactions_unique_index_drift

Revision ID: 05b84a3884b5
Revises: e3aa123ae83e
Create Date: 2026-07-08 02:51:54.978233

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05b84a3884b5"
down_revision: str | None = "e3aa123ae83e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("transactions_booking_id_key"), "transactions", type_="unique")
    op.drop_constraint(
        op.f("transactions_stripe_checkout_session_id_key"), "transactions", type_="unique"
    )
    op.drop_index(op.f("ix_transactions_booking_id"), table_name="transactions")
    op.create_index(op.f("ix_transactions_booking_id"), "transactions", ["booking_id"], unique=True)
    op.drop_index(op.f("ix_transactions_stripe_checkout_session_id"), table_name="transactions")
    op.create_index(
        op.f("ix_transactions_stripe_checkout_session_id"),
        "transactions",
        ["stripe_checkout_session_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_stripe_checkout_session_id"), table_name="transactions")
    op.create_index(
        op.f("ix_transactions_stripe_checkout_session_id"),
        "transactions",
        ["stripe_checkout_session_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_transactions_booking_id"), table_name="transactions")
    op.create_index(
        op.f("ix_transactions_booking_id"), "transactions", ["booking_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("transactions_stripe_checkout_session_id_key"),
        "transactions",
        ["stripe_checkout_session_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("transactions_booking_id_key"),
        "transactions",
        ["booking_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
