"""add_customer_onboarding_fields

Revision ID: 0958382a49ec
Revises: e5a9c3d7f1b2
Create Date: 2026-06-16 21:11:58.680676

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0958382a49ec"
down_revision: str | None = "e5a9c3d7f1b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer_profiles", sa.Column("intended_visa_type", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "customer_profiles", sa.Column("intended_destination", sa.String(length=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_profiles", "intended_destination")
    op.drop_column("customer_profiles", "intended_visa_type")
    # ### end Alembic commands ###
