"""add_booking_workflow_leads_notes_documents

Revision ID: 1fafb8833033
Revises: b8d4f6c1e2a3
Create Date: 2026-07-06 22:28:51.838956

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fafb8833033"
down_revision: str | None = "b8d4f6c1e2a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # New booking status: advisor-rejected requests, distinct from cancellations.
    op.execute("ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'rejected'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "advisor_leads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seeker_id", sa.Uuid(), nullable=False),
        sa.Column("advisor_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("match_reasons", sa.String(length=1000), nullable=False),
        sa.Column(
            "status",
            sa.Enum("new", "viewed", "contacted", "dismissed", name="advisor_lead_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["advisor_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["assessment_id"], ["assessments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seeker_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seeker_id", "advisor_id", "assessment_id"),
    )
    op.create_index(
        op.f("ix_advisor_leads_advisor_id"), "advisor_leads", ["advisor_id"], unique=False
    )
    op.create_index(
        op.f("ix_advisor_leads_assessment_id"), "advisor_leads", ["assessment_id"], unique=False
    )
    op.create_index(
        op.f("ix_advisor_leads_is_archived"), "advisor_leads", ["is_archived"], unique=False
    )
    op.create_index(
        op.f("ix_advisor_leads_seeker_id"), "advisor_leads", ["seeker_id"], unique=False
    )
    op.create_table(
        "booking_document_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum("requested", "fulfilled", name="document_request_status"),
            nullable=False,
        ),
        sa.Column("file_url", sa.String(length=500), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requested_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_document_requests_booking_id"),
        "booking_document_requests",
        ["booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_booking_document_requests_is_archived"),
        "booking_document_requests",
        ["is_archived"],
        unique=False,
    )
    op.create_index(
        op.f("ix_booking_document_requests_requested_by"),
        "booking_document_requests",
        ["requested_by"],
        unique=False,
    )
    op.create_table(
        "booking_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("booking_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_notes_author_id"), "booking_notes", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_booking_notes_booking_id"), "booking_notes", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_booking_notes_is_archived"), "booking_notes", ["is_archived"], unique=False
    )
    op.create_table(
        "booking_note_attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("note_id", sa.Uuid(), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["note_id"], ["booking_notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_booking_note_attachments_note_id"),
        "booking_note_attachments",
        ["note_id"],
        unique=False,
    )
    op.add_column(
        "bookings", sa.Column("is_important", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("bookings", sa.Column("interpreter_name", sa.String(length=255), nullable=True))
    op.add_column(
        "bookings", sa.Column("interpreter_contact", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "bookings", sa.Column("interpreter_language", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected unrelated pre-existing drift on `transactions`
    # (unique constraints vs. unique indexes) from an earlier migration/model
    # mismatch. That's outside the scope of this migration and left untouched here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "interpreter_language")
    op.drop_column("bookings", "interpreter_contact")
    op.drop_column("bookings", "interpreter_name")
    op.drop_column("bookings", "is_important")
    op.drop_index(
        op.f("ix_booking_note_attachments_note_id"), table_name="booking_note_attachments"
    )
    op.drop_table("booking_note_attachments")
    op.drop_index(op.f("ix_booking_notes_is_archived"), table_name="booking_notes")
    op.drop_index(op.f("ix_booking_notes_booking_id"), table_name="booking_notes")
    op.drop_index(op.f("ix_booking_notes_author_id"), table_name="booking_notes")
    op.drop_table("booking_notes")
    op.drop_index(
        op.f("ix_booking_document_requests_requested_by"), table_name="booking_document_requests"
    )
    op.drop_index(
        op.f("ix_booking_document_requests_is_archived"), table_name="booking_document_requests"
    )
    op.drop_index(
        op.f("ix_booking_document_requests_booking_id"), table_name="booking_document_requests"
    )
    op.drop_table("booking_document_requests")
    op.drop_index(op.f("ix_advisor_leads_seeker_id"), table_name="advisor_leads")
    op.drop_index(op.f("ix_advisor_leads_is_archived"), table_name="advisor_leads")
    op.drop_index(op.f("ix_advisor_leads_assessment_id"), table_name="advisor_leads")
    op.drop_index(op.f("ix_advisor_leads_advisor_id"), table_name="advisor_leads")
    op.drop_table("advisor_leads")
    # ### end Alembic commands ###
    # NOTE: the 'rejected' value added to booking_status in upgrade() is not
    # reversible — Postgres does not support dropping enum values.
