"""add_signup_source_and_activity_log

Revision ID: 2b00b2b88648
Revises: a49cfe988c49
Create Date: 2026-07-08 20:18:27.673768

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b00b2b88648"
down_revision: str | None = "a49cfe988c49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "occurred_on", name="uq_activity_log_user_day"),
    )
    op.create_index(
        op.f("ix_activity_logs_occurred_on"), "activity_logs", ["occurred_on"], unique=False
    )
    op.create_index(op.f("ix_activity_logs_user_id"), "activity_logs", ["user_id"], unique=False)

    # Create the enum type explicitly before adding the column that uses it.
    signup_source_enum = sa.Enum(
        "organic", "paid_ads", "referral_program", "social_media", "other", name="signup_source"
    )
    signup_source_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column("signup_source", signup_source_enum, server_default="organic", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "signup_source")
    sa.Enum(name="signup_source").drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f("ix_activity_logs_user_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_occurred_on"), table_name="activity_logs")
    op.drop_table("activity_logs")
    # ### end Alembic commands ###
