"""add_message_edit_and_delete

Revision ID: 3200952d6743
Revises: effcc875bc26
Create Date: 2026-07-07 21:42:03.984260

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3200952d6743"
down_revision: str | None = "effcc875bc26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("messages", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("messages", sa.Column("deleted_by", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected unrelated pre-existing drift on `transactions`
    # (unique constraints vs. unique indexes) from an earlier migration/model
    # mismatch. That's outside the scope of this migration and left untouched here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "deleted_by")
    op.drop_column("messages", "deleted_at")
    op.drop_column("messages", "edited_at")
    # ### end Alembic commands ###
