"""widen_admin_profile_preferred_language

Revision ID: 6f95d15d0526
Revises: b90a62a83e7c
Create Date: 2026-08-06 22:28:21.894058

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f95d15d0526"
down_revision: str | None = "b90a62a83e7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admin_profiles",
        "preferred_language",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admin_profiles",
        "preferred_language",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
