"""add_finance_management_timeline_and_partial_refunds

Revision ID: 95303b9beee8
Revises: 05b84a3884b5
Create Date: 2026-07-08 12:17:43.387932

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95303b9beee8"
down_revision: str | None = "05b84a3884b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "initiated",
                "authorized",
                "completed",
                "invoice_generated",
                "receipt_sent",
                "refunded",
                "failed",
                "closed",
                name="transaction_event_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_events_transaction_id"),
        "transaction_events",
        ["transaction_id"],
        unique=False,
    )
    op.add_column("transactions", sa.Column("refunded_amount_usd", sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate doesn't detect enum value additions — added by hand, same
    # pattern as migrations/versions/f3a1b9c7d2e4_rename_user_role_customer_to_seeker.py.
    op.execute("ALTER TYPE transaction_status ADD VALUE 'partially_refunded'")


def downgrade() -> None:
    # Postgres has no "DROP VALUE" for enums — a partially_refunded row would need
    # to be reassigned before the type could be recreated without it. Left as a
    # manual step; not attempted here since it isn't safely reversible in general.
    op.drop_column("transactions", "refunded_amount_usd")
    op.drop_index(op.f("ix_transaction_events_transaction_id"), table_name="transaction_events")
    op.drop_table("transaction_events")
    # ### end Alembic commands ###
