"""add_seeker_documents

Revision ID: e1734162178e
Revises: 1fafb8833033
Create Date: 2026-07-07 04:09:49.346803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1734162178e"
down_revision: str | None = "1fafb8833033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seeker_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seeker_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "passport",
                "educational",
                "finance",
                "supporting",
                "other",
                name="document_category",
            ),
            nullable=False,
        ),
        sa.Column("document_name", sa.String(length=255), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("under_review", "approved", "rejected", name="seeker_document_status"),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["seeker_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seeker_documents_is_archived"), "seeker_documents", ["is_archived"], unique=False
    )
    op.create_index(
        op.f("ix_seeker_documents_seeker_id"), "seeker_documents", ["seeker_id"], unique=False
    )
    op.create_table(
        "seeker_document_comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.String(length=2000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["seeker_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seeker_document_comments_author_id"),
        "seeker_document_comments",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seeker_document_comments_document_id"),
        "seeker_document_comments",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seeker_document_comments_is_archived"),
        "seeker_document_comments",
        ["is_archived"],
        unique=False,
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected unrelated pre-existing drift on `transactions`
    # (unique constraints vs. unique indexes) from an earlier migration/model
    # mismatch. That's outside the scope of this migration and left untouched here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_seeker_document_comments_is_archived"), table_name="seeker_document_comments"
    )
    op.drop_index(
        op.f("ix_seeker_document_comments_document_id"), table_name="seeker_document_comments"
    )
    op.drop_index(
        op.f("ix_seeker_document_comments_author_id"), table_name="seeker_document_comments"
    )
    op.drop_table("seeker_document_comments")
    op.drop_index(op.f("ix_seeker_documents_seeker_id"), table_name="seeker_documents")
    op.drop_index(op.f("ix_seeker_documents_is_archived"), table_name="seeker_documents")
    op.drop_table("seeker_documents")
    # ### end Alembic commands ###
