"""add_ai_assessment_admin_panel

Revision ID: e3aa123ae83e
Revises: 3200952d6743
Create Date: 2026-07-08 02:44:14.554692

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3aa123ae83e"
down_revision: str | None = "3200952d6743"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_thresholds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("visa_type", sa.String(length=50), nullable=True),
        sa.Column("highly_eligible_min", sa.Float(), nullable=False),
        sa.Column("likely_eligible_min", sa.Float(), nullable=False),
        sa.Column("borderline_min", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("country_code", "visa_type"),
    )
    op.create_index(
        op.f("ix_assessment_thresholds_country_code"),
        "assessment_thresholds",
        ["country_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_thresholds_is_archived"),
        "assessment_thresholds",
        ["is_archived"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assessment_thresholds_visa_type"),
        "assessment_thresholds",
        ["visa_type"],
        unique=False,
    )
    op.create_table(
        "eligibility_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("visa_type", sa.String(length=50), nullable=True),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("weightage_pct", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eligibility_rules_country_code"),
        "eligibility_rules",
        ["country_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eligibility_rules_is_archived"), "eligibility_rules", ["is_archived"], unique=False
    )
    op.create_index(
        op.f("ix_eligibility_rules_visa_type"), "eligibility_rules", ["visa_type"], unique=False
    )
    op.add_column(
        "assessment_questions", sa.Column("description", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected unrelated pre-existing drift on `transactions`
    # (unique constraints vs. unique indexes) from an earlier migration/model
    # mismatch. That's outside the scope of this migration and left untouched here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assessment_questions", "description")
    op.drop_index(op.f("ix_eligibility_rules_visa_type"), table_name="eligibility_rules")
    op.drop_index(op.f("ix_eligibility_rules_is_archived"), table_name="eligibility_rules")
    op.drop_index(op.f("ix_eligibility_rules_country_code"), table_name="eligibility_rules")
    op.drop_table("eligibility_rules")
    op.drop_index(op.f("ix_assessment_thresholds_visa_type"), table_name="assessment_thresholds")
    op.drop_index(op.f("ix_assessment_thresholds_is_archived"), table_name="assessment_thresholds")
    op.drop_index(op.f("ix_assessment_thresholds_country_code"), table_name="assessment_thresholds")
    op.drop_table("assessment_thresholds")
    # ### end Alembic commands ###
