"""add_payment_flow_tax_and_payouts

Revision ID: effcc875bc26
Revises: e1734162178e
Create Date: 2026-07-07 14:06:43.562305

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "effcc875bc26"
down_revision: str | None = "e1734162178e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payout_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("advisor_id", sa.Uuid(), nullable=False),
        sa.Column("amount_usd", sa.Float(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("bank_transfer", "paypal", "stripe", name="payout_method"),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("processing_fee_usd", sa.Float(), nullable=False),
        sa.Column("net_amount_usd", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "rejected", name="payout_status"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_by", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["advisor_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payout_requests_advisor_id"), "payout_requests", ["advisor_id"], unique=False
    )
    op.create_index(
        op.f("ix_payout_requests_is_archived"), "payout_requests", ["is_archived"], unique=False
    )
    # server_default values keep this safe against any existing rows — tax_usd's
    # default of 0 is a placeholder for historical rows only; all new rows get a
    # real computed value from create_checkout_session.
    op.add_column(
        "transactions", sa.Column("tax_rate", sa.Float(), nullable=False, server_default="0.08")
    )
    op.add_column(
        "transactions", sa.Column("tax_usd", sa.Float(), nullable=False, server_default="0")
    )
    op.add_column(
        "transactions",
        sa.Column("payment_method", sa.String(length=50), nullable=False, server_default="card"),
    )
    op.add_column("transactions", sa.Column("invoice_number", sa.Integer(), nullable=True))
    op.create_unique_constraint(
        "transactions_invoice_number_key", "transactions", ["invoice_number"]
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected unrelated pre-existing drift on `transactions`
    # (unique constraints vs. unique indexes) from an earlier migration/model
    # mismatch. That's outside the scope of this migration and left untouched here.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("transactions_invoice_number_key", "transactions", type_="unique")
    op.drop_column("transactions", "invoice_number")
    op.drop_column("transactions", "payment_method")
    op.drop_column("transactions", "tax_usd")
    op.drop_column("transactions", "tax_rate")
    op.drop_index(op.f("ix_payout_requests_is_archived"), table_name="payout_requests")
    op.drop_index(op.f("ix_payout_requests_advisor_id"), table_name="payout_requests")
    op.drop_table("payout_requests")
    # ### end Alembic commands ###
